import axios from "axios";

const page = async () => {
  const { data } = await axios.get(
    "https://jsonplaceholder.typicode.com/posts/1"
  );
  return <div>{JSON.stringify(data)}</div>;
};

export const metadata = {
  title: "Login - NextJS Posts App",
  description: "Generated by create next app",
};

export default page;
