import { FC, ReactNode } from "react";

interface layoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Layout - NextJS Posts App",
  description: "Generated by create next app",
};

const layout: FC<layoutProps> = ({ children }) => {
  return <div>{children}</div>;
};

export default layout;
